local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 

-- -----
--   FONT
-- -----
LSM:Register("font", "Numen", [[Interface\Addons\FojjiCore\font\Numen.ttf]])
LSM:Register("font", "FojjiArcade", [[Interface\Addons\FojjiCore\font\FojjiArcade.ttf]]) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "fojji Alarm Beep", [[Interface\Addons\FojjiCore\sound\alarmbeep.ogg]])
LSM:Register("sound", "fojji Beep", [[Interface\Addons\FojjiCore\sound\Beep.ogg]])
LSM:Register("sound", "fojji Bell", [[Interface\Addons\FojjiCore\sound\Bell.ogg]])
LSM:Register("sound", "fojji Bell: Notification", [[Interface\Addons\FojjiCore\sound\Bell Notification.ogg]])
LSM:Register("sound", "fojji Bell: Realistic", [[Interface\Addons\FojjiCore\sound\Bell Realistic.ogg]])
LSM:Register("sound", "fojji Bright Ting", [[Interface\Addons\FojjiCore\sound\Bright Ting.ogg]])
LSM:Register("sound", "fojji Chime", [[Interface\Addons\FojjiCore\sound\Chime.ogg]])
LSM:Register("sound", "fojji Click", [[Interface\Addons\FojjiCore\sound\Click.ogg]])
LSM:Register("sound", "fojji Door Alarm", [[Interface\Addons\FojjiCore\sound\Door Alarm.ogg]])
LSM:Register("sound", "fojji Drop", [[Interface\Addons\FojjiCore\sound\fojjiDrop.ogg]])
LSM:Register("sound", "fojji Gong", [[Interface\Addons\FojjiCore\sound\Gong.ogg]])
LSM:Register("sound", "fojji Heart", [[Interface\Addons\FojjiCore\sound\Heart.ogg]])
LSM:Register("sound", "fojji IM", [[Interface\Addons\FojjiCore\sound\IM.ogg]])
LSM:Register("sound", "fojji Info", [[Interface\Addons\FojjiCore\sound\Info.ogg]])
LSM:Register("sound", "fojji Kachink", [[Interface\Addons\FojjiCore\sound\Kachink.ogg]])
LSM:Register("sound", "fojji Link", [[Interface\Addons\FojjiCore\sound\Link.ogg]])
LSM:Register("sound", "fojji Mario Coin", [[Interface\Addons\FojjiCore\sound\Mario Coin.ogg]])
LSM:Register("sound", "fojji Msg", [[Interface\Addons\FojjiCore\sound\fojjiMsg.ogg]])
LSM:Register("sound", "fojji MultiPop", [[Interface\Addons\FojjiCore\sound\fojjiMultipop.ogg]])
LSM:Register("sound", "fojji MultiPop2", [[Interface\Addons\FojjiCore\sound\fojjiMultiPop2.ogg]])
LSM:Register("sound", "fojji New Notification", [[Interface\Addons\FojjiCore\sound\NewNotification.ogg]])
LSM:Register("sound", "fojji Notification", [[Interface\Addons\FojjiCore\sound\Notification.ogg]])
LSM:Register("sound", "fojji Ogre Death", [[Interface\Addons\FojjiCore\sound\fojjiOgreDeath.ogg]])
LSM:Register("sound", "fojji Pop1", [[Interface\Addons\FojjiCore\sound\fojjiPop1.ogg]])
LSM:Register("sound", "fojji Pop2", [[Interface\Addons\FojjiCore\sound\fojjiPop2.ogg]])
LSM:Register("sound", "fojji Pop3", [[Interface\Addons\FojjiCore\sound\fojjiPop3.ogg]])
LSM:Register("sound", "fojji PopClick", [[Interface\Addons\FojjiCore\sound\fojjiPopClick.ogg]])
LSM:Register("sound", "fojji Ratchet", [[Interface\Addons\FojjiCore\sound\Ratchet.ogg]])
LSM:Register("sound", "fojji Sharp Bleep", [[Interface\Addons\FojjiCore\sound\Sharp Bleep.ogg]])
LSM:Register("sound", "fojji Smooth Notify", [[Interface\Addons\FojjiCore\sound\Smooth Notify.ogg]])
LSM:Register("sound", "fojji Snap", [[Interface\Addons\FojjiCore\sound\fojjiSnap.ogg]])
LSM:Register("sound", "fojji SoftNotice", [[Interface\Addons\FojjiCore\sound\fojjiSoftNotice.ogg]])
LSM:Register("sound", "fojji Sonic Ring", [[Interface\Addons\FojjiCore\sound\SonicRing.ogg]])
LSM:Register("sound", "fojji Swoosh", [[Interface\Addons\FojjiCore\sound\fojjiSwoosh.ogg]])
LSM:Register("sound", "fojji Text1", [[Interface\Addons\FojjiCore\sound\Text1.ogg]])
LSM:Register("sound", "fojji Text2", [[Interface\Addons\FojjiCore\sound\Text2.ogg]])
LSM:Register("sound", "fojji Ting", [[Interface\Addons\FojjiCore\sound\fojjiTing.ogg]])
LSM:Register("sound", "fojji Video Game Death", [[Interface\Addons\FojjiCore\sound\fojjiVideoGameDeath.ogg]])
LSM:Register("sound", "fojji |cFFFF00001|r", [[Interface\Addons\FojjiCore\sound\1.ogg]])
LSM:Register("sound", "fojji |cFFFF00002|r", [[Interface\Addons\FojjiCore\sound\2.ogg]])
LSM:Register("sound", "fojji |cFFFF00003|r", [[Interface\Addons\FojjiCore\sound\3.ogg]])
LSM:Register("sound", "fojji |cFFFF00004|r", [[Interface\Addons\FojjiCore\sound\4.ogg]])
LSM:Register("sound", "fojji |cFFFF00005|r", [[Interface\Addons\FojjiCore\sound\5.ogg]])
LSM:Register("sound", "fojji |cFFFF00006|r", [[Interface\Addons\FojjiCore\sound\6.ogg]])
LSM:Register("sound", "fojji |cFFFF00007|r", [[Interface\Addons\FojjiCore\sound\7.ogg]])
LSM:Register("sound", "fojji |cFFFF00008|r", [[Interface\Addons\FojjiCore\sound\8.ogg]])
LSM:Register("sound", "fojji |cFFFF00009|r", [[Interface\Addons\FojjiCore\sound\9.ogg]])
LSM:Register("sound", "fojji |cFFFE000010|r", [[Interface\Addons\FojjiCore\sound\10.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Berserk|r", [[Interface\Addons\FojjiCore\sound\Berserk.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Berserk Soon|r", [[Interface\Addons\FojjiCore\sound\Berserk Soon.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Clear|r", [[Interface\Addons\FojjiCore\sound\Clear.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Interrupt|r", [[Interface\Addons\FojjiCore\sound\Interrupt.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Phase2|r", [[Interface\Addons\FojjiCore\sound\Phase2.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Phase3|r", [[Interface\Addons\FojjiCore\sound\Phase3.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Phase4|r", [[Interface\Addons\FojjiCore\sound\Phase4.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Soulwell|r", [[Interface\Addons\FojjiCore\sound\Soulwell.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Taunt|r", [[Interface\Addons\FojjiCore\sound\Taunt.ogg]])
LSM:Register("sound", "fojji |cFFFF0000Watch your feet|r", [[Interface\Addons\FojjiCore\sound\Watch your feet.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000FurtherBeyond|r", [[Interface\Addons\FojjiCore\sound\FurtherBeyond.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000GaryMeow|r", [[Interface\Addons\FojjiCore\sound\GaryMeow.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000Light Saber|r", [[Interface\Addons\FojjiCore\sound\Lightsaber.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000BombHasBeenPlanted|r", [[Interface\Addons\FojjiCore\sound\BombHasBeenPlanted.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000TerroristsWin|r", [[Interface\Addons\FojjiCore\sound\TerroristsWin.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000MarioLevelComplete|r", [[Interface\Addons\FojjiCore\sound\MarioLevelComplete.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000BowlingPins|r", [[Interface\Addons\FojjiCore\sound\BowlingPins.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000HomeAlabama|r", [[Interface\Addons\FojjiCore\sound\HomeAlabama.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000HallelujahShort|r", [[Interface\Addons\FojjiCore\sound\HallelujahShort.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000OhShitOhShit|r", [[Interface\Addons\FojjiCore\sound\OhShitOhShit.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000Heavenly|r", [[Interface\Addons\FojjiCore\sound\Heavenly.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000BlowItOut|r", [[Interface\Addons\FojjiCore\sound\BlowItOut.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000TPIRLoseHorn|r", [[Interface\Addons\FojjiCore\sound\TPIRLoseHorn.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000YesYesBison|r", [[Interface\Addons\FojjiCore\sound\YesYesBison.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000SadTrombone|r", [[Interface\Addons\FojjiCore\sound\SadTrombone.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000MetalGearAlert|r", [[Interface\Addons\FojjiCore\sound\MetalGearAlert.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000MarioKartRaceStart|r", [[Interface\Addons\FojjiCore\sound\MarioKartRaceStart.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000MarioJump|r", [[Interface\Addons\FojjiCore\sound\MarioJump.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000MarioShell|r", [[Interface\Addons\FojjiCore\sound\MarioShell.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000WilheimScream|r", [[Interface\Addons\FojjiCore\sound\WilheimScream.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000Bruh|r", [[Interface\Addons\FojjiCore\sound\Bruh.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000ManScreaming|r", [[Interface\Addons\FojjiCore\sound\ManScreaming.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000TisButAScratch|r", [[Interface\Addons\FojjiCore\sound\TisButAScratch.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000ItsJustAFleshWound|r", [[Interface\Addons\FojjiCore\sound\ItsJustAFleshWound.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000RetroShot|r", [[Interface\Addons\FojjiCore\sound\RetroShot.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF00008BitLoseLife|r", [[Interface\Addons\FojjiCore\sound\8BitLoseLife.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000Mario-Jump|r", [[Interface\Addons\FojjiCore\sound\Mario-Jump.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000MarioYoshi|r", [[Interface\Addons\FojjiCore\sound\MarioYoshi.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000JackInTheBox|r", [[Interface\Addons\FojjiCore\sound\JackInTheBox.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000SpringJump|r", [[Interface\Addons\FojjiCore\sound\SpringJump.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000Squish|r", [[Interface\Addons\FojjiCore\sound\Squish.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000Tetsu5Sunders|r", [[Interface\Addons\FojjiCore\sound\Tetsu5Sunders.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000TetsuDeadActually|r", [[Interface\Addons\FojjiCore\sound\TetsuDeadActually.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000JoardeeLosingMyMind|r", [[Interface\Addons\FojjiCore\sound\JoardeeLosingMyMind.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000JoardeeImAFuckingGamer|r", [[Interface\Addons\FojjiCore\sound\JoardeeImAFuckingGamer.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000JoardeeMassiveThingOnAss|r", [[Interface\Addons\FojjiCore\sound\JoardeeMassiveThingOnAss.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000Run|r", [[Interface\Addons\FojjiCore\sound\Run.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000ShadeChant|r", [[Interface\Addons\FojjiCore\sound\ShadeChant.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000WelcomeToJurassicPark|r", [[Interface\Addons\FojjiCore\sound\WelcomeToJurassicPark.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000DinosaurRoar|r", [[Interface\Addons\FojjiCore\sound\DinosaurRoar.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000LifeUhFindsAWay|r", [[Interface\Addons\FojjiCore\sound\LifeUhFindsAWay.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000DinosaurEat|r", [[Interface\Addons\FojjiCore\sound\DinosaurEat.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000CleverGirl|r", [[Interface\Addons\FojjiCore\sound\CleverGirl.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000DinosaurEat2|r", [[Interface\Addons\FojjiCore\sound\DinosaurEat2.ogg]])
LSM:Register("sound", "fojjiMeme |cFFFF0000JurassicParkTheme|r", [[Interface\Addons\FojjiCore\sound\JurassicParkTheme.ogg]])

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "fojjiBlank", [[Interface\Addons\FojjiCore\statusbar\fojjiBlank.tga]])
LSM:Register("statusbar", "fojjiFlat", [[Interface\Addons\FojjiCore\statusbar\fojjiFlat.tga]])
LSM:Register("statusbar", "fojjiKUI", [[Interface\Addons\FojjiCore\statusbar\fojjiKUI.tga]])
LSM:Register("statusbar", "fojjiMelli", [[Interface\Addons\FojjiCore\statusbar\Melli.tga]])